image: $REGISTRY_CI/gitlab-ci-base:buster

stages:
- build-test
- test
- package
- build
- deploy

variables:
  DOCKER_HOST: tcp://localhost:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:19.03.1-dind

#########################
####  TEMPLATE      ####
########################

.test_template: &test_definition
  stage: test
  tags:
    - gcp-cypress-runner
  allow_failure: false
  before_script:
    - sed -i -e "s/{HIPAY_API_USER_TEST\}/$HIPAY_API_USER_TEST/" ./bin/docker/conf/test/hipay.env.sample
    - sed -i -e "s/{HIPAY_API_PASSWORD_TEST\}/$HIPAY_API_PASSWORD_TEST/" ./bin/docker/conf/test/hipay.env.sample
    - sed -i -e "s/{HIPAY_TOKENJS_PUBLICKEY_TEST\}/$HIPAY_TOKENJS_PUBLICKEY_TEST/" ./bin/docker/conf/test/hipay.env.sample
    - sed -i -e "s/{HIPAY_TOKENJS_USERNAME_TEST\}/$HIPAY_TOKENJS_USERNAME_TEST/" ./bin/docker/conf/test/hipay.env.sample
    - sed -i -e "s/{HIPAY_SECRET_PASSPHRASE_TEST\}/$HIPAY_SECRET_PASSPHRASE_TEST/" ./bin/docker/conf/test/hipay.env.sample
    - sed -i "s/$(echo {HIPAY_SECRET_PASSPHRASE_TEST} | sed -e 's/\([[\/.*]\|\]\)/\\&/g')/$(echo '$HIPAY_SECRET_PASSPHRASE_TEST' | sed -e 's/[\/&]/\\&/g')/g" ./bin/docker/conf/test/hipay.env.sample
    - sed -i -e "s@{PI_CI_DATA_URL\}@$PI_CI_DATA_URL@" ./bin/docker/conf/test/hipay.env.sample
    - cp ./bin/tests/.npmrc.sample ./bin/tests/.npmrc
    - sed -i -e "s/\${NPM_REGISTRY_TOKEN\}/$NPM_REGISTRY_TOKEN/" ./bin/tests/.npmrc
    - docker-compose -f docker-compose.test.yml pull
    - docker-compose -f docker-compose.test.yml up -d
    - cd bin/tests
    - yarn install
    - cd ../../
    - until docker-compose -f docker-compose.test.yml logs | grep -m 1 "DOCKER WOOCOMMERCE TO HIPAY stage IS UP" ; do sleep 10 ; done
    - docker-compose -f docker-compose.test.yml logs
    - curl --retry 10 --retry-delay 20 -v http:\/\/localhost:8000
    - cd bin/tests
  artifacts:
    paths:
      - bin/tests/cypress/videos
      - bin/tests/cypress/screenshots
    when: always
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-tests/

#########################
####  JOBS          ####
########################

build-test:
  stage: build-test
  script:
    - docker-compose -f docker-compose.test.yml build
    - docker-compose -f docker-compose.test.yml push
  tags:
    - gcp-default-runner

test-cypress-1:
  <<: *test_definition
  script:
    - bash /tools/run-cypress-test.sh -f $TESTS_FOLDERS_1 -e $EXCLUDED_TEST_FILES --config baseUrl=http://localhost:8000 --env $CYPRESS_ENV
    - docker logs wordpress_web 2> tmperror2.log 1> /dev/null
    - sed -i 's/, referer:.*$//g' tmperror2.log
    - if [ "$(grep -i "^\[.*hipay" tmperror2.log)" != "" ]; then grep -i "^\[.*hipay" tmperror2.log; exit 1; fi

test-cypress-2:
  <<: *test_definition
  script:
    - bash /tools/run-cypress-test.sh -f $TESTS_FOLDERS_2 -e $EXCLUDED_TEST_FILES --config baseUrl=http://localhost:8000 --env $CYPRESS_ENV
    - docker logs wordpress_web 2> tmperror2.log 1> /dev/null
    - sed -i 's/, referer:.*$//g' tmperror2.log
    - if [ "$(grep -i "^\[.*hipay" tmperror2.log)" != "" ]; then grep -i "^\[.*hipay" tmperror2.log; exit 1; fi

package:
  stage: package
  before_script:
    - apt-get install -y zip sshpass
  script:
    - echo "Package module $CI_COMMIT_REF_SLUG"
    - cd src/woocommerce_hipayenterprise
    - composer install --no-dev
    - cd ../..
    - ./bin/package/builder.sh -v $CI_COMMIT_REF_SLUG
  artifacts:
    paths:
      - ./bin/package
  tags:
    - gcp-default-runner

build:
  stage: build
  when: manual
  before_script:
    - bash /tools/auth-to-cd-registry.sh
  script:
    - docker build -f bin/docker/images/woocommerce/Dockerfile . -t ${REGISTRY_CD}/${DOCKER_STACK}-${DOCKER_SERVICE}-web:${CI_COMMIT_REF_SLUG}
    - docker push ${REGISTRY_CD}/${DOCKER_STACK}-${DOCKER_SERVICE}-web:${CI_COMMIT_REF_SLUG}
  tags:
    - gcp-default-runner

deploy2recette:
  stage: deploy
  before_script:
    - bash /tools/auth-to-cd-cluster.sh
  script:
    - echo ${DOCKER_STACK}-${DOCKER_SERVICE}-${CI_COMMIT_REF_SLUG}
    - helm install $DOCKER_STACK-$DOCKER_SERVICE-$CI_COMMIT_REF_SLUG ./bin/docker/kubernetes/helm/
  allow_failure: true
  tags:
  - gcp-default-runner
  when: manual
  environment:
    name: review/${CI_COMMIT_REF_SLUG}
    url: https://${DOCKER_STACK}-${DOCKER_SERVICE}-${CI_COMMIT_REF_SLUG}.${PI_CD_URL}
    on_stop: stop_review
  only:
    - branches

stop_review:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  before_script:
    # Get GCP credentials as file
    - echo $GCP_CD_CLUSTER_SERVICE_ACCOUNT_KEY_FILE > ${HOME}/gcloud-service-key.json
    # Auth gcloud with key file
    - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
    # Rm auth file
    - rm ${HOME}/gcloud-service-key.json
    # Set current project
    - gcloud config set project $GCP_CD_PROJECT_ID
    - gcloud container clusters get-credentials cd-pi-poc
  script:
    - helm uninstall ${DOCKER_STACK}-${DOCKER_SERVICE}-${CI_COMMIT_REF_SLUG}
  when: manual
  environment:
    name: review/${CI_COMMIT_REF_SLUG}
    action: stop
  tags:
    - gcp-default-runner
